######################################################################
# Automatically generated by qmake (3.0) Do. Sep. 25 18:40:14 2014
######################################################################

QT = core gui widgets

TEMPLATE = lib
INCLUDEPATH += ../lib/

CONFIG += staticlib link_pkgconfig
PKGCONFIG +=

# Input
HEADERS += ahp.h
FORMS += ahp.ui
SOURCES += ahp.cpp main.cpp
